// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH-zweVD6DRKP8WvyZdOjLfiJPNEuAVpw',
    appId: '1:230311438050:android:53ebacd2d33e85c04560bb',
    messagingSenderId: '230311438050',
    projectId: 'simpleshoppingapp-f391c',
    storageBucket: 'simpleshoppingapp-f391c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDCfO0yzfi0uhtxt5X5b42sB0DmBzPDHQ',
    appId: '1:230311438050:ios:5eae948e565ba0304560bb',
    messagingSenderId: '230311438050',
    projectId: 'simpleshoppingapp-f391c',
    storageBucket: 'simpleshoppingapp-f391c.firebasestorage.app',
    iosBundleId: 'com.example.shoppingAppWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI-086nO9q4-_QztrOxg45zssjRzfGdC8',
    appId: '1:230311438050:web:e6a13599ade342944560bb',
    messagingSenderId: '230311438050',
    projectId: 'simpleshoppingapp-f391c',
    authDomain: 'simpleshoppingapp-f391c.firebaseapp.com',
    storageBucket: 'simpleshoppingapp-f391c.firebasestorage.app',
    measurementId: 'G-LC60RZP32E',
  );
}
